const express = require("express")
const dotenv = require("dotenv")
dotenv.config()
const cors = require("cors")
const app = express()
const { getConnect } = require("./ConnectDB/ConnectDb")
const cityRouter = require("./Routes/Cityrouter")
const packageRouer = require("./Routes/Packagerouter")
const includeRouter = require("./Routes/Includerouter")
const FlightRouter = require("./Routes/FlightRouter")
const HotelRouter = require("./Routes/HotelRouter")
const ContactRouter = require("./Routes/ContactRouter")
const PackageInquery = require("./Routes/PackageInqueryRouter")
getConnect()

app.use(cors())
app.use(express.json())
app.set(express.static("./Public"))

app.use("/api" ,cityRouter)
app.use("/api" ,packageRouer)
app.use("/api" ,includeRouter)
app.use("/api" ,FlightRouter)
app.use("/api" ,HotelRouter)
app.use("/api" ,ContactRouter)
app.use("/api" ,PackageInquery)

app.listen(process.env.PORT, () => {
    console.log(`Server is running at ${process.env.PORT} port`)
})
